### PR TITLE
Clean code for Fahrenheit units

### PR DESCRIPTION
**Pull request by martinezpenya**
Added rain_rate, removed Fahrenheit unit conversion

### CODE REVIEW

**Review by pilotak — CHANGES_REQUESTED** [review]
Because you removed everything with appendix `_f` it would be good to actually remove appendix `_c` from left over. What do you think?

**Comment by martinezpenya** [comment]
It's good for me.

**Comment by martinezpenya** [comment]
I think you have all `_c` appendixes removed.

**Comment by pilotak** [comment]
perfect, thanks

**Review by pilotak — APPROVED** [review]

**Pull request merged**
